### ISSUE TITLE
Fix Profile Share button for some users

### ISSUE THREAD

**Issue by sarveshpro** [Plant-for-the-Planet-org/planet-webapp#540]
location - logged in user profile
the close button goes behind the facebook icon
![image (1)](https://user-images.githubusercontent.com/27153515/100895803-f7876c00-34e3-11eb-8981-fa7c4895db98.png)

**Comment by norbertschuler** [comment]
We had that before when the German translations got so big that the buttons got wider. I thought it was fixed by @captainamiedi ?

**Comment by captainamiedi** [comment]
> We had that before when the German translations got so big that the buttons got wider. I thought it was fixed by @captainamiedi ?

These has been fixed. I can't produce these error. maybe @sarveshpro can help us produce it

**Comment by sarveshpro** [comment]
This was encountered by a team member from the German Office.

URL: https://planet-webapp-ccc6o2k43.vercel.app/
Browser: Firefox 83.0 
OS: Ubuntu

If this is already fixed you can mark it as can not reproduce and close it.

**Comment by norbertschuler** [comment]
Sometimes this still happens for me, e.g. on https://planet-webapp-ccc6o2k43.vercel.app/t/norbert-schuler

**Comment by harshvitra** [comment]
Cannot replicate. 
Closing since no re-occurrence has been reported

**Comment by norbertschuler** [comment]
I just saw this again at https://planet-webapp-o4j9y6spb.vercel.app/t/norbert-schuler in https://github.com/Plant-for-the-Planet-org/planet-webapp/pull/777 as following in my profile:
<img width="405" alt="Bildschirmfoto 2021-01-29 um 19 23 40" src="https://user-images.githubusercontent.com/1532418/106312807-89eb8800-6267-11eb-9b57-8b214815dc48.png">

**Comment by norbertschuler** [comment]
This is not fixed, testing https://planet-webapp-ijycemkj3-planetapp.vercel.app/t/sagar-aryal shows when clicking the German share button in latest Chrome on latest MacOS:

<img width="605" alt="Bildschirmfoto 2021-02-24 um 20 07 34" src="https://user-images.githubusercontent.com/1532418/109052529-fe391000-76db-11eb-88dd-d7744efa7f8c.png">
